### ISSUE TITLE
Error when docker-compose up

### ISSUE THREAD

**Issue by t2lc** [BretFisher/php-docker-good-defaults#1]
Hi,

I just git clone the folder, "cd" to the folder and then run docker-compose up. Instantly I have the following error:

> ERROR: The Compose file './docker-compose.yml' is invalid because:
services.php.environment.APP_DEBUG contains true, which is an invalid type, it should be a string, number, or a null

I guess I can change the value to 1, but I'm not sure. This is why I'm opening this ticket :)

Thanks.

Regards,

Thibault

**Comment by BretFisher** [comment]
Thanks, fixed!
