### ISSUE TITLE
Node things in Dockerfile

### ISSUE THREAD

**Issue by alexakarpov** [BretFisher/php-docker-good-defaults#14]
Hi Bret,

I am very confused... the title and README of this repo suggest it's a good starting place for a php website... but why  does it also has npm and node all over the Dockerfile and README? It seems to contradict the "good defaults" notion...
Finally, docker build is failing; the error is quite impossible to read, too - the "command" that fails is basically a whole script in itself:

$ docker build . -f base-php-nginx.Dockerfile

> Step 10/16 : RUN curl -s -f -L -o /tmp/installer.php https://raw.githubusercontent.com/composer/getcomposer.org/da290238de6d63faace0343efbdd5aa9354332c5/web/installer  && php -r "     \$signature = '669656bab3166a7aff8a7506b8cb2d1c292f042046c5a994c43155c0be6190fa0355160742ab2e1c88d40d5be660b410';     \$hash = hash('SHA384', file_get_contents('/tmp/installer.php'));     if (!hash_equals(\$signature, \$hash)) {         unlink('/tmp/installer.php');         echo 'Integrity check failed, installer is either corrupt or worse.' . PHP_EOL;         exit(1);     }"  && php /tmp/installer.php --no-ansi --install-dir=/usr/bin --filename=composer --version=${COMPOSER_VERSION}  && rm /tmp/installer.php  && composer --ansi --version --no-interaction
>  ---> Running in cc7074642068
> All settings correct for using Composer
> SHA384 is not supported by your openssl extension
> The command '/bin/sh -c curl -s -f -L -o /tmp/installer.php https://raw.githubusercontent.com/composer/getcomposer.org/da290238de6d63faace0343efbdd5aa9354332c5/web/installer  && php -r "     \$signature = '669656bab3166a7aff8a7506b8cb2d1c292f042046c5a994c43155c0be6190fa0355160742ab2e1c88d40d5be660b410';     \$hash = hash('SHA384', file_get_contents('/tmp/installer.php'));     if (!hash_equals(\$signature, \$hash)) {         unlink('/tmp/installer.php');         echo 'Integrity check failed, installer is either corrupt or worse.' . PHP_EOL;         exit(1);     }"  && php /tmp/installer.php --no-ansi --install-dir=/usr/bin --filename=composer --version=${COMPOSER_VERSION}  && rm /tmp/installer.php  && composer --ansi --version --no-interaction' returned a non-zero code: 1
>

**Comment by BretFisher** [comment]
Yep, it's *work in progress* but haven't had much help with it and so it's not in the best shape.

Many PHP apps need npm inside them for dependencies, and the docs were taken from my nodejs example repo so maybe it's a bit confusing. PR's welcome!

**Comment by alexakarpov** [comment]
gotcha, thanks Bret; now that I got some context, I will consider it )
