### ISSUE TITLE
Why not simply use php-apache?

### ISSUE THREAD

**Issue by vctls** [BretFisher/php-docker-good-defaults#15]
Any reason why we should prefer a custom php image with nginx and supervisor, rather than just using the official php-apache image?
I know there are performance variations between the different php/apache/nginx configurations, but I'm not sure they're critical.
Also, we can still scale the backend using replicas if needed, right?
And maybe just put php-apache behind a caching proxy.

**Comment by BretFisher** [comment]
php-fpm is generally the standard for large scale solutions. Sure you can work around mod_php limitations like you suggested, or you could just use php-fpm with nginx :)

**Comment by vctls** [comment]
Ok, so no major difference here, then? Works for me :) Thanks!
