### ISSUE TITLE
Entrypoint script missing inside container

### ISSUE THREAD

**Issue by aadilacetrot** [BretFisher/php-docker-good-defaults#21]
docker-php-entrypoint and docker-php-entrypoint-dev script is not copied to the container in the base image. Was it on purpose?

**Comment by BretFisher** [comment]
There are two images in this repo, one depends on the other, and the main one (that gets app-specific COPY) is where those are copied in: https://github.com/BretFisher/php-docker-good-defaults/blob/master/Dockerfile#L70
