### ISSUE TITLE
Dockerfile ssh-keyscan fails

### ISSUE THREAD

**Issue by ab0ris** [BretFisher/php-docker-good-defaults#6]
Image build fails for me on this step:
> RUN ssh-keyscan -t rsa bitbucket.org >> /root/.ssh/known_hosts \
>          && ssh-keyscan -t rsa github.com >> /root/.ssh/known_hosts

with the following error:
>/bin/sh: 1: cannot create /root/.ssh/known_hosts: Directory nonexistent

Let's change it to
> RUN mkdir /root/.ssh && chmod 0700 /root/.ssh \
>    && ssh-keyscan -t rsa bitbucket.org >> /root/.ssh/known_hosts \
>    && ssh-keyscan -t rsa github.com >> /root/.ssh/known_hosts

what do you think?

**Comment by BretFisher** [comment]
Yea let me change that, thanks!

**Comment by BretFisher** [comment]
Fixed, thanks @b0ric
