### ISSUE TITLE
docker-php-entrypoint-dev cache and build folders

### ISSUE THREAD

**Issue by jstowey** [BretFisher/php-docker-good-defaults#9]
Hey,

I'm just wondering why the /var/www/app/build and /var/www/app/cache directories exist within the entry point script? These aren't folders that normally exist with a standard Laravel installation so maybe I'm missing something but would be great to know why they're included?

Thanks

**Comment by BretFisher** [comment]
There examples of how you might deal with permissions, even during local development when bind-mounting files. This repo is not just for Laravel, but for all PHP users :)

**Comment by jstowey** [comment]
Ah, my apologies, I've just got blinkers on for Laravel based projects atm!
